// <auto-generated />
using System;
using InventorySync.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventorySync.Infrastructure.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20260923210145_ReportingIndexes")]
    partial class ReportingIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventorySync.Core.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ErpRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LocallyModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("WarehouseCode")
                        .HasDatabaseName("IX_InventoryItems_Whse_Valuation");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("WarehouseCode"), new[] { "QuantityOnHand", "UnitCost" });

                    b.HasIndex("WarehouseCode", "LastSyncedUtc");

                    b.HasIndex("WarehouseCode", "QuantityOnHand")
                        .HasDatabaseName("IX_InventoryItems_LowStock")
                        .HasFilter("QuantityOnHand < 25");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("InventorySync.Core.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErpRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpectedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LocallyModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PoNumber")
                        .IsUnique();

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PurchaseOrders_OpenByStatus")
                        .HasFilter("Status IN (1, 2)");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status"), new[] { "Id", "PoNumber" });

                    b.ToTable("PurchaseOrders", (string)null);
                });

            modelBuilder.Entity("InventorySync.Core.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("Sku")
                        .HasDatabaseName("IX_PurchaseOrderLines_Sku_Open");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Sku"), new[] { "QuantityOrdered", "QuantityReceived" });

                    b.ToTable("PurchaseOrderLines", (string)null);
                });

            modelBuilder.Entity("InventorySync.Core.Entities.SyncAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SyncRunId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Action", "TimestampUtc")
                        .HasDatabaseName("IX_SyncAuditEntries_Action_TimestampUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Action", "TimestampUtc"), new[] { "SyncRunId" });

                    b.HasIndex("SyncRunId", "EntityType");

                    b.ToTable("SyncAuditEntries", (string)null);
                });

            modelBuilder.Entity("InventorySync.Core.Entities.SyncRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<int?>("ParentSyncRunId")
                        .HasColumnType("int");

                    b.Property<int>("RecordsFailed")
                        .HasColumnType("int");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("int");

                    b.Property<int>("RecordsRead")
                        .HasColumnType("int");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentSyncRunId");

                    b.HasIndex("EntityType", "StartedUtc");

                    b.ToTable("SyncRuns", (string)null);
                });

            modelBuilder.Entity("InventorySync.Core.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("InventorySync.Core.Entities.PurchaseOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventorySync.Core.Entities.SyncAuditEntry", b =>
                {
                    b.HasOne("InventorySync.Core.Entities.SyncRun", null)
                        .WithMany()
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventorySync.Core.Entities.SyncRun", b =>
                {
                    b.HasOne("InventorySync.Core.Entities.SyncRun", "ParentSyncRun")
                        .WithMany()
                        .HasForeignKey("ParentSyncRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentSyncRun");
                });

            modelBuilder.Entity("InventorySync.Core.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
